# -*- coding: utf-8 -*-
"""trying10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rILu_t5NCTyw-kQBFS44OViMwMbzmhzV
"""

# Install pakages
! pip install pandas scikit-learn scikit-image statsmodels requests dash

# Neccesary imports
import logging
import shlex
import subprocess
import sys
import platform
import shutil
import google.colab
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from collections import namedtuple
from matplotlib.patches import Rectangle
from matplotlib.collections import PatchCollection

logging.basicConfig(level=logging.ERROR)

# Clone, clear if needed
shutil.rmtree('/content/final-project-image-crop')
! git clone https://github.com/sreeram315/final-project-image-crop
sys.path.append("final-project-image-crop/src")

# Define file paths
bin_dir     = Path("final-project-image-crop/bin")
bin_path    = "final-project-image-crop/binData/candidate_crops"
model_path  = "final-project-image-crop/binData/fastgaze.vxm"
data_dir    = Path("final-project-image-crop/data")
img_path    = Path("/content/final-project-image-crop/data/input.jpeg")
print("\n")
print(f"Image is at: {str(img_path.absolute())}")
print(f"Model is at: {str(model_path)}")
print("\n")

# Display original image
img         = mpimg.imread(img_path)
plt.imshow(img)
plt.gca().add_patch(Rectangle((0, 0), 200, 112, linewidth=1, edgecolor="b", facecolor="none"))
plt.title("Original Image")

# Get models output 
command = f"{str(bin_path)} {str(model_path)} '{img_path.absolute()}' show_all_points"
output = subprocess.check_output(command, shell=True)

# Show crop part for different aspect ratios
from crop_api import ImageSaliencyModel, is_symmetric, parse_output, reservoir_sampling
model = ImageSaliencyModel(crop_binary_path=bin_path, crop_model_path=model_path)
saliencyData = model.plot_img_crops(img_path)

# Crop images for different aspect ratios, with saliency coordinate as centre point

from fractions import Fraction
from utils import cropImage
! mkdir photos

absoluteImagePath = str(img_path.absolute())
aspectRatios = [0.3125, 0.625, 1.0, 1.14, 2]
salientCoordinates = saliencyData['salient_coordinates']
print("Aspect Ratios are:")
for ratio in aspectRatios:
  fraction = Fraction(ratio).limit_denominator(10)
  height = fraction.numerator
  width = fraction.denominator
  print(f"Aspect Width: {width} Height: {height}")
  cropImage(absoluteImagePath, (width, height), salientCoordinates, f"photos/{ratio}")

# Download the folder to view photos
! zip -r photos.zip photos
from google.colab import files
files.download("photos.zip")